[package]
name = "example"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kti_cqrs_rs = { path = "../kti_cqrs_rs" }
tokio = { version = "1.42.0", features = ["macros", "sync", "rt", "time"] }
async-trait = "0.1.83"
