[package]
name = "kti_cqrs_rs"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Implementation of CQRS pattern in Rust"
homepage = "https://github.com/kotletti/kti_cqrs_rs"
repository = "https://github.com/kotletti/kti_cqrs_rs"
readme = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.73"
